/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek1;

import javax.swing.JOptionPane;

/**
 *
 * @author Windows 10
 */
public class Pendaftaran extends javax.swing.JFrame {
    private boolean isinamaClicked = false;
    private boolean isinimClicked = false;
    private boolean isittlClicked = false;
    private boolean isialamatClicked = false;
    private boolean isifakultasClicked = false;
    private boolean isinohpClicked = false;
    private boolean AlasanClicked = false;



    /**
     * Creates new form Pendaftaran
     */
    public Pendaftaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Panel1 = new javax.swing.JPanel();
        logoutm = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul4 = new javax.swing.JLabel();
        judul3 = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        Formulir = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        NamaLengkap = new javax.swing.JLabel();
        NIM = new javax.swing.JLabel();
        TTL = new javax.swing.JLabel();
        jeniskelamin = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        Fakultas = new javax.swing.JLabel();
        nohp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alasan = new javax.swing.JTextArea();
        isinama = new javax.swing.JTextField();
        isinim = new javax.swing.JTextField();
        isittl = new javax.swing.JTextField();
        isinohp = new javax.swing.JTextField();
        isialamat = new javax.swing.JTextField();
        tbsimpan = new javax.swing.JButton();
        tbexit = new javax.swing.JButton();
        tbreset = new javax.swing.JButton();
        lakilaki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        isifakultas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Panel1.setBackground(new java.awt.Color(204, 204, 255));
        Panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek1/utm.png"))); // NOI18N
        Panel1.add(logoutm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 90));

        judul2.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        judul2.setText("UNIVERSITAS TRUNOJOYO MADURA");
        Panel1.add(judul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        judul1.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        judul1.setText("UNIT KEGIATAN MAHASISWA");
        Panel1.add(judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        judul4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        judul4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul4.setText("Telp : (031) 3011146, Fax. (031) 3011506");
        Panel1.add(judul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, 30));

        judul3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        judul3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul3.setText("Jl. Raya Telang, PO. Box. 2 Kamal, Bangkalan - Madura");
        Panel1.add(judul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        getContentPane().add(Panel1);
        Panel1.setBounds(0, 0, 450, 90);

        Panel2.setBackground(new java.awt.Color(255, 204, 255));
        Panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Formulir.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        Formulir.setText("FORMULIR PENDAFTARAN UKM");

        foto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto.setText("Photo 3x4");
        foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NamaLengkap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        NamaLengkap.setText("Nama Lengkap       : ");

        NIM.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        NIM.setText("NIM                      : ");

        TTL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TTL.setText("TTL                      : ");

        jeniskelamin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jeniskelamin.setText("Jenis Kelamin         : ");

        Alamat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Alamat.setText("Alamat                   : ");

        Fakultas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Fakultas.setText("Fakultas                 :");

        nohp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nohp.setText("NO. Hp                  :");

        Alasan.setBackground(new java.awt.Color(255, 204, 255));
        Alasan.setColumns(20);
        Alasan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Alasan.setRows(5);
        Alasan.setText(" Berikan alasanmu disini");
        Alasan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Alasan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlasanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Alasan);

        isinama.setBackground(new java.awt.Color(255, 204, 255));
        isinama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isinama.setText(".............................................");
        isinama.setBorder(null);
        isinama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isinamaMouseClicked(evt);
            }
        });

        isinim.setBackground(new java.awt.Color(255, 204, 255));
        isinim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isinim.setText(".............................................");
        isinim.setBorder(null);
        isinim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isinimMouseClicked(evt);
            }
        });

        isittl.setBackground(new java.awt.Color(255, 204, 255));
        isittl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isittl.setText(".............................................");
        isittl.setBorder(null);
        isittl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isittlMouseClicked(evt);
            }
        });

        isinohp.setBackground(new java.awt.Color(255, 204, 255));
        isinohp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isinohp.setText(".............................................");
        isinohp.setBorder(null);
        isinohp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isinohpMouseClicked(evt);
            }
        });

        isialamat.setBackground(new java.awt.Color(255, 204, 255));
        isialamat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isialamat.setText(".............................................");
        isialamat.setBorder(null);
        isialamat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isialamatMouseClicked(evt);
            }
        });

        tbsimpan.setBackground(new java.awt.Color(0, 255, 0));
        tbsimpan.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        tbsimpan.setForeground(new java.awt.Color(255, 255, 255));
        tbsimpan.setText("SIMPAN");
        tbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbsimpanActionPerformed(evt);
            }
        });

        tbexit.setBackground(new java.awt.Color(255, 0, 0));
        tbexit.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        tbexit.setForeground(new java.awt.Color(255, 255, 255));
        tbexit.setText("EXIT");
        tbexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbexitActionPerformed(evt);
            }
        });

        tbreset.setBackground(new java.awt.Color(255, 255, 51));
        tbreset.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        tbreset.setForeground(new java.awt.Color(255, 255, 255));
        tbreset.setText("RESET");
        tbreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbresetActionPerformed(evt);
            }
        });

        buttonGroup1.add(lakilaki);
        lakilaki.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lakilaki.setText("Laki-laki");
        lakilaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakilakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(perempuan);
        perempuan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        perempuan.setText("Perempuan");
        perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanActionPerformed(evt);
            }
        });

        isifakultas.setBackground(new java.awt.Color(255, 204, 255));
        isifakultas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        isifakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fakultas Ekonomi dan Bisnis", "Fakultas Hukum", "Fakultas Keislaman", "Fakultas Pertanian", "Fakultas Pendidikan", "Fakultas Teknik", "Fakultas Ilmu Sosial dan Budaya" }));
        isifakultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isifakultasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(Formulir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(NamaLengkap)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isinama, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(NIM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isinim, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(TTL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isittl, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(jeniskelamin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lakilaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(perempuan)))
                        .addGap(18, 18, 18)
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(tbsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(tbreset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbexit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(nohp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isinohp, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(Alamat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isialamat, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel2Layout.createSequentialGroup()
                                .addComponent(Fakultas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isifakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Formulir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamaLengkap)
                            .addComponent(isinama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NIM)
                            .addComponent(isinim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TTL)
                            .addComponent(isittl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jeniskelamin)
                            .addComponent(lakilaki)
                            .addComponent(perempuan))))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alamat)
                    .addComponent(isialamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fakultas)
                    .addComponent(isifakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nohp)
                    .addComponent(isinohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbreset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbexit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(Panel2);
        Panel2.setBounds(0, 90, 450, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbsimpanActionPerformed
        String Nama, Nim, TTL, Fakultas, nohp, Alamat, alasan,jk;
        Nama = isinama.getText();
        Nim = isinim.getText();
        TTL = isittl.getText();
        Fakultas = (String) isifakultas.getSelectedItem();
        nohp = isinohp.getText();
        Alamat = isialamat.getText();
        alasan = Alasan.getText();
        
        if(lakilaki.isSelected()){
            jk = "Laki-laki";
        }
        else {
            jk = "Perempuan";
        }
        
        JOptionPane.showMessageDialog(null, "Nama : " + Nama 
                                                         + "\n Nim : " + Nim 
                                                         + "\n TTL : " + TTL
                                                         + "\n Jenis Kelamin : " + jk
                                                         + "\n Alamat : " + Alamat
                                                         + "\n Fakultas/Prodi : " + Fakultas
                                                         + "\n No. Hp : " + nohp
                                                         + "\n \n Alasan : " + alasan, "DATA TERSIMPAN",JOptionPane.INFORMATION_MESSAGE);

        
        
    }//GEN-LAST:event_tbsimpanActionPerformed

    private void tbexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_tbexitActionPerformed

    private void tbresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbresetActionPerformed
        isinama.setText(".............................................");
        isinim.setText(".............................................");
        isittl.setText(".............................................");
        isifakultas.setSelectedIndex(0);
        isialamat.setText(".............................................");
        isinohp.setText(".............................................");
        Alasan.setText("Berikan Alasanmu disini");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_tbresetActionPerformed

    private void lakilakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakilakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakilakiActionPerformed

    private void perempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanActionPerformed

    private void isinamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isinamaMouseClicked
        if (!isinamaClicked) {
            isinama.setText(""); 
            isinamaClicked = true; 
        }
    }//GEN-LAST:event_isinamaMouseClicked

    private void isinimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isinimMouseClicked
        if (!isinimClicked) {
            isinim.setText(""); 
            isinimClicked = true; 
        }
    }//GEN-LAST:event_isinimMouseClicked

    private void isittlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isittlMouseClicked
        if (!isittlClicked) {
            isittl.setText(""); 
            isittlClicked = true; 
        }
    }//GEN-LAST:event_isittlMouseClicked

    private void isialamatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isialamatMouseClicked
        if (!isialamatClicked) {
            isialamat.setText(""); 
            isialamatClicked = true; 
        }
    }//GEN-LAST:event_isialamatMouseClicked

    private void isinohpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isinohpMouseClicked
        if (!isinohpClicked) {
            isinohp.setText(""); 
            isinohpClicked = true; 
        }
    }//GEN-LAST:event_isinohpMouseClicked

    private void AlasanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlasanMouseClicked
        if (!AlasanClicked) {
            Alasan.setText(""); 
            AlasanClicked = true; 
        }
    }//GEN-LAST:event_AlasanMouseClicked

    private void isifakultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isifakultasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_isifakultasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JTextArea Alasan;
    private javax.swing.JLabel Fakultas;
    private javax.swing.JLabel Formulir;
    private javax.swing.JLabel NIM;
    private javax.swing.JLabel NamaLengkap;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JLabel TTL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel foto;
    private javax.swing.JTextField isialamat;
    private javax.swing.JComboBox<String> isifakultas;
    private javax.swing.JTextField isinama;
    private javax.swing.JTextField isinim;
    private javax.swing.JTextField isinohp;
    private javax.swing.JTextField isittl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jeniskelamin;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel judul4;
    private javax.swing.JRadioButton lakilaki;
    private javax.swing.JLabel logoutm;
    private javax.swing.JLabel nohp;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton tbexit;
    private javax.swing.JButton tbreset;
    private javax.swing.JButton tbsimpan;
    // End of variables declaration//GEN-END:variables
}
